{% set name = "snowflake-ml-python" %}
{% set version = "1.7.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a5e00a002b80eb805e79c5396ad232976405728d4cf5223191e3e7ad671d1da5

build:
  # The build number of this package should always start from 100
  # for new versions. For more information ask the CODEOWNERS.
  number: 100
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<39 or py>312]
  # snowflake-snowpark-python, snowflake-connector-python, pytimeparse packages are not available on s390x target
  skip: True  # [s390x]

requirements:
  host:
    - python
    - pip
    - setuptools >=61.0
    - wheel
  run:
    - python
    - absl-py >=0.15,<2
    # For fsspec[http] in conda
    - aiohttp !=4.0.0a0,!=4.0.0a1
    - anyio >=3.5.0,<5
    - cloudpickle >=2.0.0
    - cryptography
    - fsspec >=2024.6.1,<2026
    - importlib_resources >=6.1.1,<7
    - numpy >=1.23,<2
    - packaging >=20.9,<25
    - pandas >=1.0.0,<3
    - pyarrow
    - pyjwt >=2.0.0,<3
    - pyyaml >=6.0,<7
    # requests is an extra dependency for fsspec[http]
    - requests
    - retrying >=1.3.3,<2
    - s3fs >=2024.6.1,<2026
    - scikit-learn >=1.4,<1.6
    - scipy >=1.9,<2
    - snowflake-connector-python >=3.5.0,<4
    - snowflake-snowpark-python >=1.17.0,<2,!=1.26.0
    - sqlparse >=0.4,<1
    - typing-extensions >=4.1.0,<5
    - xgboost >=1.7.3,<3
    - cachetools >=3.1.1,<6
    - pytimeparse >=1.1.8,<2
  run_constrained:
    - catboost >=1.2.0,<2
    - lightgbm >=4.1.0,<5
    - mlflow >=2.16.0,<3
    - pytorch >=2.0.1,<3
    - sentence-transformers >=2.7.0,<3
    - sentencepiece >=0.1.95,<0.2.0
    - shap >=0.46.0,<1
    - tensorflow >=2.17.0,<3
    - tokenizers >=0.15.1,<1
    - torchdata >=0.4,<1
    - transformers >=4.37.2,<5
    - keras >=2.0.0,<4

test:
  imports:
    - snowflake.ml
    - snowflake.ml.fileset
    - snowflake.ml.model
    - snowflake.ml.modeling
    - snowflake.ml.registry
    - snowflake.ml.utils
    - snowflake.cortex
  commands:
    - pip check
    # check that pip gets the correct version
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
  requires:
    - pip

about:
  home: https://github.com/snowflakedb/snowflake-ml-python
  summary: Snowflake machine learning library.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  description: |
    The machine learning client library that is used for interacting with Snowflake
    to build machine learning solutions. Functionalities include model uploading,
    training, feature engineering, etc.
  dev_url: https://github.com/snowflakedb/snowflake-ml-python
  doc_url: https://docs.snowflake.com/developer-guide/snowflake-ml/overview

extra:
  recipe-maintainers:
    - sumit0190
