{% set name = "snowflake-ml-python" %}
{% set version = "1.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 71a939f14796bb67932dcc94f46f44b5e6e0c1a0c91e68b393d4591d31cc98ea

build:
  # The build number of this package should always start from 100
  # for new versions. For more information ask the CODEOWNERS.
  number: 100
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<39 or py>312]

requirements:
  host:
    - python
    - pip
    - setuptools >=61.0
  run:
    - python
    # For fsspec[http] in conda
    - aiohttp !=4.0.0a0,!=4.0.0a1
    - anyio >=3.5.0,<5
    - cachetools >=3.1.1,<6
    - cloudpickle >=2.0.0
    - cryptography
    - fsspec >=2024.6.1,<2026
    # requests is an extra dependency for fsspec[http]
    - requests
    - importlib_resources >=6.1.1,<7
    - numpy >=1.23,<3
    - packaging >=20.9,<25
    - pandas >=2.1.4,<3
    - platformdirs <5
    - pyarrow <19.0.0
    - pydantic >=2.8.2,<3
    - pyjwt >=2.0.0,<3
    - pytimeparse >=1.1.8,<2
    - pyyaml >=6.0,<7
    - retrying >=1.3.3,<2
    - s3fs >=2024.6.1,<2026
    - scikit-learn <1.8
    - scipy >=1.9,<2
    - shap >=0.46.0,<1
    - snowflake-connector-python >=3.16.0,<4
    - snowflake-snowpark-python >=1.17.0,<2,!=1.26.0
    - snowflake.core >=1.0.2,<2
    - sqlparse >=0.4,<1
    - tqdm <5
    - typing-extensions >=4.1.0,<5
    - xgboost >=1.7.3,<3
  run_constrained:
    - altair >=5,<6
    - catboost >=1.2.0,<2
    - keras >=2.0.0,<4
    - lightgbm >=4.1.0,<5
    - mlflow >=2.16.0,<3
    - sentence-transformers >=2.7.0,<4
    - sentencepiece >=0.1.95,<0.2.0
    - streamlit >=1.30.0,<2
    - tensorflow >=2.17.0,<3
    - tokenizers >=0.15.1,<1
    - pytorch >=2.0.1,<3
    - torchdata >=0.4,<1
    - transformers >=4.39.3,<5,!=4.51.3

test:
  imports:
    - snowflake.ml
    - snowflake.ml._internal
    - snowflake.ml.fileset
    - snowflake.ml.model
    - snowflake.ml.modeling
    - snowflake.ml.registry
    - snowflake.ml.utils
    - snowflake.cortex
    - snowflake.ml.data
    - snowflake.ml.dataset
    - snowflake.ml.feature_store
    - snowflake.ml.jobs
    - snowflake.ml.lineage
    - snowflake.ml.monitoring
    - snowflake.ml.utils
    - snowflake.ml.version
  commands:
    - pip check
    # check that pip gets the correct version
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # Tests/LLM testing is not possible without an active connection to Snowflake environment.
  requires:
    - pip

about:
  home: https://github.com/snowflakedb/snowflake-ml-python
  summary: Snowflake machine learning library.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  description: |
    The machine learning client library that is used for interacting with Snowflake
    to build machine learning solutions. Functionalities include model uploading,
    training, feature engineering, etc.
  dev_url: https://github.com/snowflakedb/snowflake-ml-python
  doc_url: https://docs.snowflake.com/developer-guide/snowflake-ml/overview

extra:
  recipe-maintainers:
    - sumit0190