{% set name = "snowflake-ml-python" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/snowflakedb/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: f3ed8227e358a80831cbd938b446531b74140f675d07c2d9107919d5313c35e5

build:
  number: 0
  skip: True # [py<38 or py>311]
  # Skip Windows (on CI) because it needs a manual build for now.
  # Skip s390x and ppc64 since they lack bazel.
  skip: True # [s390x]
  # skipping win until build pipeline for win works
  skip: True # [win]

requirements:
  build:
    - git         # [not win]
    # Bazel has rules to run Miniconda to build the package so make sure that the Miniconda and conda-libmamba-solver versions are correct, 
    # because it can affect the build process, see https://github.com/snowflakedb/snowflake-ml-python/blob/main/third_party/rules_conda/conda.bzl
    - bazel 6.2.0
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - absl-py >=0.15,<2
    - aiohttp !=4.0.0a0,!=4.0.0a1
    - anyio >=3.5.0,<4
    - cloudpickle >=2.0.0
    - fsspec >=2022.11,<2024
    - importlib_resources >=5.1.4,<6
    - numpy >=1.23,<2
    - packaging >=20.9,<24
    - pandas >=1.0.0,<2
    - pyarrow
    - python
    - pyyaml >=6.0,<7
    # requests is an extra dependency for fsspec[http]
    - retrying >=1.3.3,<2
    - requests
    - s3fs >=2022.11,<2024
    - scikit-learn >=1.2.1,<1.4
    - scipy >=1.9,<2
    - snowflake-connector-python >=3.0.4,<4
    - snowflake-snowpark-python >=1.8.0,<2,!=1.12.0
    - sqlparse >=0.4,<1
    - typing-extensions >=4.1.0,<5
    - xgboost >=1.7.3,<2
    - cachetools >=3.1.1,<6
    - pytimeparse >=1.1.8,<2

  run_constrained:
    # Seems to be optional
    - shap ==0.42.1
    # Seems to be optional to LLM although not explicitly used. Also, not sure if pip will install it.
    - sentencepiece >=0.1.95,<0.2
    # Seems to be optional depending on task executed within huggingface pipeline, but it's listed as part of transformers.
    # Also, not sure if pip will install it, also there is inconsistency as far as range requirement. (less restrictive one seems to be >=0.10,<1)
    - tokenizers >=0.13.3
    # these dependencies are specified as optional and also in a run_contrained section of their recipe
    # but in reality they may always be imported, hence they should be specified in the run section
    # ...
    # seems to be imported when LLM is used
    # we don't have this on defaults or other channels
    - peft >=0.5.0,<1
    # seems to be required by one specific model specification builder
    - lightgbm ==3.3.5
    # seems to be required by one specific model handler
    - mlflow >=2.1.0,<2.4
    # seems to be required in multiple places, especially LLM which seems to be included, also on all platforms, not just win
    - pytorch <2.1.0
    # seems to be required in multiple places
    # requiring this as a run dependency seems to cause a lot of dependency problems.
    - tensorflow >=2.10,<3
    # Seems to be depepndent on pytorch, so not optional
    - torchdata >=0.4,<1
    # seems to be in multiple places, especially LLM which seems to be included
    - transformers >=4.32.1,<5
    # seems to be required by one specific model handler
    - sentence-transformers >=2.2.2,<3

test:
  imports:
    - snowflake.ml
    - snowflake.ml.fileset
    - snowflake.ml.model
    - snowflake.ml.modeling
    - snowflake.ml.registry
    - snowflake.ml.utils
  requires:
    - pip
  commands:
    # On win-64 this does not pick up xgboost for some reason, so skip it.
    - pip check   # [not win]

about:
  home: https://github.com/snowflakedb/snowflake-ml-python
  summary: Snowflake machine learning library.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  description: |
    The machine learning client library that is used for interacting with Snowflake
    to build machine learning solutions. Functionalities include model uploading,
    training, feature engineering, etc.
  dev_url: https://github.com/snowflakedb/snowflake-ml-python
  doc_url: https://docs.snowflake.com/developer-guide/snowpark-ml/index

extra:
  recipe-maintainers:
    - sumit0190
