{% set name = "snowflake-ml-python" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/snowflakedb/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6badcd1d89e9562d0f2ad3ce67129431c299458e68c32cf71de00ef7b8d31206
  patches:
    - fix-windows-build.patch                # [win64]

build:
  number: 0
  # Skip 3.11 as snowpark isn't available on 3.11 yet.
  skip: True # [py<38 or py>310]
  # Skip Windows (on CI) because it needs a manual build for now.
  # Skip s390x and ppc64 since they lack bazel.
  skip: True # [s390x or ppc64le or win]

requirements:
  build:
    - git         # [not win]
    - m2-patch    # [win64]
    - python
    - setuptools
    - wheel
    - bazel 6.2.0
  run:
    - absl-py >=0.15,<2
    - aiohttp !=4.0.0a0,!=4.0.0a1
    - anyio >=3.5.0,<4
    - cloudpickle
    - fsspec >=2022.11,<=2023.1
    - numpy >=1.23,<2
    - packaging >=20.9,<24
    - pandas >=1.0.0,<2
    - python
    - pyyaml >=6.0,<7
    - requests
    - scikit-learn >=1.2.1,<1.3
    - scipy >=1.9,<2
    - snowflake-connector-python >=3.0.3,<4
    - snowflake-snowpark-python >=1.5.1,<2
    - sqlparse >=0.4,<1
    - typing-extensions >=4.1.0,<5
    - xgboost >=1.7.3,<2
  run_constrained:
    - lightgbm==3.3.5
    - tensorflow >=2.9,<3
    - torchdata >=0.4,<1
    - mlflow >=2.1.0,<3

test:
  imports:
    - snowflake.ml
  requires:
    - pip
  commands:
    # On win-64 this does not pick up xgboost for some reason, so skip it.
    - pip check   # [not win]

about:
  home: https://github.com/snowflakedb/snowflake-ml-python
  summary: Snowflake machine learning library.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  description: |
    The machine learning client library that is used for interacting with Snowflake
    to build machine learning solutions. Functionalities include model uploading,
    training, feature engineering, etc.
  dev_url: https://github.com/snowflakedb/snowflake-ml-python
  doc_url: https://docs.snowflake.com/developer-guide/snowpark-ml/index

extra:
  recipe-maintainers:
    - sumit0190
